### PR TITLE
N3GOV-19: Basic Income for Nation3 Citizens

### PR DESCRIPTION
**Pull request by aahna-ashina**
https://forum.nation3.org/t/proposal-basic-income-for-nation3-citizens/754

Followed the proposal submission instructions at https://github.com/nation3/gov/blob/main/GOVERNANCE.md#submitting-a-proposal

### CODE REVIEW

**Comment by aahna-ashina** [comment]
@luisivan I lack access to add people as reviewers to pull requests in this repo.

**Comment by luisivan** [comment]
@aahna-ashina added!

In terms of the proposal, shouldn't this be an Expense, since it will move funds?

**Comment by aahna-ashina** [comment]
> shouldn't this be an Expense, since it will move funds?

@luisivan You mean funds will be moved from the DAO to the multi-sig?

Should I change to this?

```json

    "kind": "expense",
    "transfers": [
      {
        "chainId": 1,
        "from": "0x336252602b3a8a0be336ed942228305173e8082b",
        "recipient": "0x7fFf737ae9FdDD6E28Fe8B8F0F4dE69Bb8e7a885",
        "token": "0x333A4823466879eeF910A04D473505da62142069",
        "amount": 36000000000000000000
      }
    ]
```

**Comment by luisivan** [comment]
Exactly @aahna-ashina, and then the Meta Guild multisig can handle the payment schedules. BTW amount should be the human-readable amount (e.g. 3.6 $NATION) instead of wei.

**Comment by aahna-ashina** [comment]
> BTW amount should be the human-readable amount (e.g. 3.6 $NATION) instead of wei.

@luisivan Thanks, I made the adjustments 👍

**Comment by luisivan** [comment]
@aahna-ashina once the proposal is frozen, feel free to add the `frozen` tag

**Comment by aahna-ashina** [comment]
> once the proposal is frozen, feel free to add the `frozen` tag

@luisivan I don't have GitHub access to add labels to this PR:

> Screen Shot 2022-09-20 at 8 29 00 AM

**Comment by luisivan** [comment]
@aahna-ashina while I figure out how to configure permissions, let me know whenever you want to freeze it

**Comment by aahna-ashina** [comment]
> while I figure out how to configure permissions, let me know whenever you want to freeze it

@luisivan All right.  Unless there are any unanswered questions in the forum thread, I think we can freeze it now 😄

**Comment by luisivan** [comment]
@aahna-ashina congrats on your first governance proposal, it's been merged 🥳

**Pull request merged**
