### PR TITLE
N3GOV-26

### PR DESCRIPTION
**Pull request by luisivan**

### CODE REVIEW

**Review by aahna-ashina — COMMENTED** [review]
Rename the file from -X to -26?

**Comment by luisivan** [comment]
Technically the governance process states it should be `N3GOV-X.json`, but it doesn't specify whether the X is a placeholder to leave until a reviewer assigns a number, or the actual self-assigned number 😆  Anyway, I moved the file

**Comment by aahna-ashina** [comment]
@luisivan Got it.  Maybe some of these steps can be automated also (to avoid human error).

**Comment by luisivan** [comment]
@aahna-ashina would love to automate this workflow. Ideally a bot checks the payload against the spec and automatically merges if the forum post has been out more than 48h

**Pull request merged**
